In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
ratings_df = pd.read_csv("ratings.csv")

In [3]:
books_df = pd.read_csv("books.csv")

In [4]:
rating_max = ratings_df["rating"].max()

In [5]:
rating_min = ratings_df["rating"].min()

In [6]:
rating_max,rating_min

(5, 1)

In [7]:
booksId_max = books_df["book_id"].max()

In [8]:
booksId_max

10000

In [9]:
userId_max = ratings_df["user_id"].max()

In [10]:
userId_max

53424

In [11]:
selectUserId = int(input("请输入你要推荐的用户ID："))

请输入你要推荐的用户ID：5


In [12]:
selectUserId 

5

In [13]:
selectUser_bookList = ratings_df.loc[ratings_df["user_id"]==selectUserId]["book_id"].values

In [14]:
selectUser_bookList

array([7601,  441, 6344, 4335, 1485, 1145, 2592,  431,  326,  887, 6014,
       3037, 1795,  305, 1339,   57, 8072, 4187, 5791, 4897, 8884, 4997,
       6774, 2637, 1742, 3267, 4829, 7591,  262, 4736, 2813,  164, 2888,
       8258,  112,  695, 4305, 1328, 3559, 3429,  458, 1009,  277, 3378,
       7141, 2207, 1563, 1195,    6, 1347, 1325,  623, 6510, 4131, 1182,
       5289, 8143,  473, 5167, 3744, 4539, 2431, 1770, 7474, 5143, 4344,
       6404, 7891, 4947,  626, 4247, 1723, 2396,  253, 1628, 6703,  794,
       5766, 3647, 1882, 2602, 3380, 1744, 1911,  139, 4380, 4546, 5117,
       6151, 4942,  451, 1345, 3691,  852, 4786, 7933, 6646, 1941, 4011,
       7487], dtype=int64)

In [15]:
selectUser_bookList.shape

(100,)

In [16]:
simUserCount = np.zeros(userId_max,dtype=np.int)

In [17]:
simUserCount.shape

(53424,)

In [18]:
print(simUserCount)

[0 0 0 ... 0 0 0]


In [19]:
for index,row in ratings_df.iterrows():
    if row["book_id"] in selectUser_bookList:
        simUserCount[row["user_id"]] = simUserCount[row["user_id"]]+1

In [20]:
simUserCount

array([0, 2, 0, ..., 0, 1, 2])

In [21]:
simUserId = np.argsort(-simUserCount)

In [22]:
trainUserId = simUserId[0:50]

In [23]:
trainUserId = trainUserId.tolist()

In [24]:
trainUserId

[5,
 4068,
 19029,
 13550,
 266,
 1602,
 6795,
 2826,
 16606,
 16066,
 1480,
 4427,
 47012,
 44069,
 25520,
 35588,
 7570,
 2899,
 22101,
 2167,
 2199,
 2358,
 26093,
 51814,
 22276,
 16126,
 2330,
 50439,
 18355,
 32160,
 20374,
 41861,
 43050,
 3642,
 1192,
 107,
 33147,
 18369,
 29972,
 1976,
 6184,
 17120,
 49330,
 26830,
 46227,
 22436,
 14213,
 5200,
 41356,
 6385]

In [25]:
trainBookId = []

In [26]:
for index,row in ratings_df.iterrows():
    if row["user_id"] in trainUserId and row["book_id"]  not in trainBookId:
        trainBookId.append(row["book_id"])

In [27]:
trainBookId

[958,
 7733,
 8934,
 2621,
 5215,
 7059,
 4395,
 82,
 1650,
 40,
 45,
 344,
 326,
 217,
 1401,
 3333,
 7426,
 7471,
 9731,
 5206,
 8349,
 8446,
 9748,
 8781,
 199,
 111,
 233,
 62,
 368,
 480,
 8847,
 1003,
 3758,
 637,
 866,
 377,
 46,
 1873,
 516,
 321,
 2320,
 278,
 50,
 11,
 94,
 236,
 316,
 239,
 322,
 283,
 666,
 167,
 481,
 117,
 110,
 2321,
 289,
 281,
 86,
 123,
 1186,
 13,
 192,
 130,
 32,
 7285,
 3,
 688,
 687,
 605,
 49,
 52,
 56,
 2084,
 3671,
 4915,
 694,
 174,
 47,
 5179,
 4971,
 26,
 9,
 1607,
 3705,
 7211,
 84,
 575,
 1117,
 1817,
 5201,
 5764,
 7351,
 726,
 7180,
 2890,
 8541,
 6277,
 9981,
 8418,
 8756,
 8972,
 5,
 1586,
 28,
 343,
 833,
 1388,
 1245,
 1407,
 1733,
 963,
 1301,
 488,
 705,
 703,
 37,
 1154,
 868,
 1623,
 7466,
 2910,
 9199,
 2989,
 4673,
 2560,
 191,
 258,
 3788,
 4836,
 1,
 4920,
 2423,
 917,
 6686,
 67,
 8814,
 98,
 7031,
 1669,
 8417,
 534,
 5818,
 3605,
 3213,
 2824,
 1230,
 1052,
 205,
 8422,
 1655,
 38,
 1485,
 2371,
 64,
 331,
 616,
 908,
 477

In [28]:
trainUserNo,trainBookNo = len(trainUserId),len(trainBookId)

In [29]:
trainUserNo,trainBookNo

(50, 2383)

In [30]:
train_ratings = np.zeros((trainUserNo,trainBookNo),dtype=np.float32)

In [31]:
for index,row in ratings_df.iterrows():
    if row["user_id"] in trainUserId and row["book_id"] in trainBookId:
        train_ratings[trainUserId.index(row["user_id"])][trainBookId.index(row["book_id"])] = row["rating"]

In [32]:
train_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 4., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [33]:
train_record = train_ratings>0

In [34]:
train_record = np.array(train_record,dtype=int)

In [35]:
train_record

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [36]:
temSum = 0.0
train_count = 0
for i in range(0,trainUserNo):
    for j in range(0,trainBookNo):
        if train_ratings[i][j] != 0. :
            temSum = temSum + train_ratings[i][j]
            train_count = train_count+1
train_global_rating_mean = temSum/train_count

In [94]:
train_global_rating_mean

3.790372193171332

In [122]:
f = 10
lamda = 0.01

In [123]:
def createBSVD(mean,userNo,bookNo,f):
    BIAS_u = train_global_rating_mean
    BIAS_bu = tf.Variable(tf.zeros((userNo,1),dtype=tf.float32))
    BIAS_bi = tf.Variable(tf.zeros((1,bookNo),dtype=tf.float32))
    BIAS_P = tf.Variable(tf.random_normal([userNo,f],stddev=1/(f**0.5),dtype=tf.float32))
    BIAS_Q = tf.Variable(tf.random_normal([bookNo,f],stddev=1/(f**0.5),dtype=tf.float32))
    BIAS_predict_rating = BIAS_u + BIAS_bu + BIAS_bi + tf.matmul(BIAS_P,BIAS_Q,transpose_b=True)
    BIAS_loss = tf.reduce_sum(((train_ratings-BIAS_predict_rating)*train_record)**2) + lamda*((tf.reduce_sum(BIAS_P)**2) + (tf.reduce_sum(BIAS_Q)**2) + (tf.reduce_sum(BIAS_bu)**2) + (tf.reduce_sum(BIAS_bi)**2))
    return BIAS_loss,BIAS_predict_rating

In [124]:
loss,predict = createBSVD(train_global_rating_mean,trainUserNo,trainBookNo,f)

In [125]:
learning_rate = 1e-4

In [126]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate)

In [127]:
train = optimizer.minimize(loss)

In [128]:
sess = tf.Session()

In [129]:
init = tf.global_variables_initializer()

In [130]:
sess.run(init)

In [131]:
for i in range(1000): 
    if i % 100 == 0:
        print(i)
    sess.run(train)

0
100
200
300
400
500
600
700
800
900


In [132]:
predict_rating = sess.run(predict)

In [133]:
predict_rating

array([[4.479424 , 4.512636 , 4.083194 , ..., 4.0508633, 4.020274 ,
        4.0423   ],
       [2.895513 , 3.5214272, 4.014535 , ..., 3.469405 , 3.5842602,
        3.5335968],
       [4.881831 , 4.396787 , 4.140667 , ..., 4.5440125, 4.833091 ,
        4.6426954],
       ...,
       [3.128574 , 3.3536737, 3.8105323, ..., 3.8704035, 3.4639852,
        3.2353802],
       [5.0358543, 4.3196564, 3.6462862, ..., 4.20662  , 4.387491 ,
        4.080234 ],
       [4.9986043, 4.5349874, 4.160006 , ..., 4.32909  , 4.251503 ,
        3.905489 ]], dtype=float32)

In [134]:
selectUser_predictRating = predict_rating[0]

In [135]:
selectUser_predictRating

array([4.479424 , 4.512636 , 4.083194 , ..., 4.0508633, 4.020274 ,
       4.0423   ], dtype=float32)

In [136]:
selectUser_sortRating = np.argsort(-selectUser_predictRating)

In [137]:
selectUser_sortRating

array([1761,  487, 1089, ...,  687,  764, 1047], dtype=int64)

In [138]:
predict_rating_sort = np.sort(selectUser_predictRating)[::-1]

In [139]:
predict_rating_sort

array([5.247857 , 5.147886 , 5.0338616, ..., 2.59724  , 2.5589042,
       2.484163 ], dtype=float32)

In [140]:
predict_bookId = []
for i in range(0,trainBookNo):
    predict_bookId.append(trainBookId[selectUser_sortRating[i]])

In [141]:
predict_bookId

[267,
 520,
 1462,
 25,
 6895,
 1913,
 3911,
 4029,
 827,
 3329,
 459,
 3756,
 2610,
 4498,
 458,
 21,
 98,
 2320,
 3059,
 164,
 10,
 630,
 3124,
 192,
 4639,
 874,
 5794,
 249,
 261,
 2375,
 4706,
 1182,
 5289,
 1459,
 1496,
 9139,
 638,
 3247,
 258,
 9791,
 3193,
 8422,
 4247,
 24,
 8371,
 3946,
 188,
 2789,
 1241,
 131,
 6,
 39,
 5191,
 4947,
 27,
 1882,
 2890,
 5217,
 4552,
 2538,
 794,
 3205,
 7557,
 8198,
 6729,
 37,
 696,
 1653,
 422,
 364,
 6720,
 2614,
 1631,
 1709,
 5462,
 1196,
 176,
 168,
 2554,
 1301,
 7424,
 273,
 1248,
 773,
 3744,
 1711,
 335,
 602,
 1304,
 1068,
 608,
 8813,
 1792,
 89,
 397,
 8333,
 18,
 495,
 17,
 285,
 100,
 8608,
 4815,
 378,
 8184,
 731,
 3355,
 47,
 653,
 1308,
 278,
 3208,
 7109,
 421,
 4025,
 1317,
 291,
 840,
 4103,
 1728,
 737,
 210,
 914,
 553,
 1630,
 123,
 1152,
 451,
 430,
 3257,
 172,
 1868,
 2290,
 5167,
 7401,
 4856,
 649,
 2055,
 5243,
 1713,
 6025,
 5822,
 281,
 6549,
 2771,
 7487,
 2445,
 2570,
 2215,
 4412,
 2555,
 1052,
 883,
 434

In [142]:
recomResult = {}
for i in range(0,20):
    recomResult[predict_bookId[i]] = predict_rating_sort[i]

In [143]:
recomResult.keys()

dict_keys([267, 520, 1462, 25, 6895, 1913, 3911, 4029, 827, 3329, 459, 3756, 2610, 4498, 458, 21, 98, 2320, 3059, 164])

In [149]:
recomlist = recomResult.keys()

In [151]:
for bid in recomlist:
    if bid in selectUser_bookList:
        recomResult.pop(bid)

In [152]:
books_df.head()

book_id  goodreads_book_id  best_book_id  work_id  books_count       isbn  \
0        1            2767052       2767052  2792775          272  439023483   
1        2                  3             3  4640799          491  439554934   
2        3              41865         41865  3212258          226  316015849   
3        4               2657          2657  3275794          487   61120081   
4        5               4671          4671   245494         1356  743273567   

         isbn13                      authors  original_publication_year  \
0  9.780439e+12              Suzanne Collins                     2008.0   
1  9.780440e+12  J.K. Rowling, Mary GrandPré                     1997.0   
2  9.780316e+12              Stephenie Meyer                     2005.0   
3  9.780061e+12                   Harper Lee                     1960.0   
4  9.780743e+12          F. Scott Fitzgerald                     1925.0   

                             original_title  \
0                          The Hunger Games   
1  Harry Potter and the Philosopher's Stone   
2                                  Twilight   
3                     To Kill a Mockingbird   
4                          The Great Gatsby   

                         ...                         ratings_count  \
0                        ...                               4780653   
1                        ...                               4602479   
2                        ...                               3866839   
3                        ...                               3198671   
4                        ...                               2683664   

  work_ratings_count  work_text_reviews_count  ratings_1  ratings_2  \
0            4942365                   155254      66715     127936   
1            4800065                    75867      75504     101676   
2            3916824                    95009     456191     436802   
3            3340896                    72586      60427     117415   
4            2773745                    51992      86236     197621   

   ratings_3  ratings_4  ratings_5  \
0     560092    1481305    2706317   
1     455024    1156318    3011543   
2     793319     875073    1355439   
3     446835    1001952    1714267   
4     606158     936012     947718   

                                           image_url  \
0  https://images.gr-assets.com/books/1447303603m...   
1  https://images.gr-assets.com/books/1474154022m...   
2  https://images.gr-assets.com/books/1361039443m...   
3  https://images.gr-assets.com/books/1361975680m...   
4  https://images.gr-assets.com/books/1490528560m...   

                                     small_image_url  
0  https://images.gr-assets.com/books/1447303603s...  
1  https://images.gr-assets.com/books/1474154022s...  
2  https://images.gr-assets.com/books/1361039443s...  
3  https://images.gr-assets.com/books/1361975680s...  
4  https://images.gr-assets.com/books/1490528560s...  

[5 rows x 23 columns]

In [153]:
print("为用户ID为：%d的用户推荐的10本书是：" % (selectUserId))
idx = 1
for bid,prating in recomResult.items():
    bookname = books_df.loc[books_df["book_id"]==bid]["original_title"].values[0]
    print("第 %d 本图书id为  %d ，书名为：%s ，评分为：%.2f" % (idx,bid,bookname,prating))
    if idx == 10:
        break
    idx = idx +1

为用户ID为：5的用户推荐的10本书是：
第 1 本图书id为  267 ，书名为：The Nightingale ，评分为：5.25
第 2 本图书id为  520 ，书名为：ねじまき鳥クロニクル [Nejimakidori kuronikuru] ，评分为：5.15
第 3 本图书id为  1462 ，书名为：The Orphan Master's Son ，评分为：5.03
第 4 本图书id为  25 ，书名为：Harry Potter and the Deathly Hallows ，评分为：5.01
第 5 本图书id为  6895 ，书名为：How We Are Hungry ，评分为：4.98
第 6 本图书id为  1913 ，书名为：Rachel's Holiday ，评分为：4.97
第 7 本图书id为  3911 ，书名为：Drown ，评分为：4.93
第 8 本图书id为  4029 ，书名为：The Son ，评分为：4.92
第 9 本图书id为  827 ，书名为：To All the Boys I've Loved Before ，评分为：4.92
第 10 本图书id为  3329 ，书名为：The Heart Goes Last ，评分为：4.91
